from ..errors import DockerException as DockerException
from typing import Any

class CancellableStream:
    def __init__(self, stream, response) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...
    next: Any
    def close(self) -> None: ...
