from .. import errors as errors, utils as utils
from typing import Any

class VolumeApiMixin:
    def volumes(self, filters: Any | None = ...): ...
    def create_volume(
        self,
        name: Any | None = ...,
        driver: Any | None = ...,
        driver_opts: Any | None = ...,
        labels: Any | None = ...,
    ): ...
    def inspect_volume(self, name): ...
    def prune_volumes(self, filters: Any | None = ...): ...
    def remove_volume(self, name, force: bool = ...) -> None: ...
