from .version import version as version
from typing import Any

DEFAULT_DOCKER_API_VERSION: str
MINIMUM_DOCKER_API_VERSION: str
DEFAULT_TIMEOUT_SECONDS: int
STREAM_HEADER_SIZE_BYTES: int
CONTAINER_LIMITS_KEYS: Any
DEFAULT_HTTP_HOST: str
DEFAULT_UNIX_SOCKET: str
DEFAULT_NPIPE: str
BYTE_UNITS: Any
INSECURE_REGISTRY_DEPRECATION_WARNING: str
IS_WINDOWS_PLATFORM: Any
WINDOWS_LONGPATH_PREFIX: str
DEFAULT_USER_AGENT: Any
DEFAULT_NUM_POOLS: int
DEFAULT_NUM_POOLS_SSH: int
DEFAULT_MAX_POOL_SIZE: int
DEFAULT_DATA_CHUNK_SIZE: Any
DEFAULT_SWARM_ADDR_POOL: Any
DEFAULT_SWARM_SUBNET_SIZE: int
