import requests
from typing import Any

class DockerException(Exception): ...

def create_api_error_from_http_exception(e) -> None: ...

class APIError(requests.exceptions.HTTPError, DockerException):
    response: Any
    explanation: Any
    def __init__(
        self, message, response: Any | None = ..., explanation: Any | None = ...
    ) -> None: ...
    @property
    def status_code(self): ...
    def is_error(self): ...
    def is_client_error(self): ...
    def is_server_error(self): ...

class NotFound(APIError): ...
class ImageNotFound(NotFound): ...
class InvalidVersion(DockerException): ...
class InvalidRepository(DockerException): ...
class InvalidConfigFile(DockerException): ...
class InvalidArgument(DockerException): ...
class DeprecatedMethod(DockerException): ...

class TLSParameterError(DockerException):
    msg: Any
    def __init__(self, msg) -> None: ...

class NullResource(DockerException, ValueError): ...

class ContainerError(DockerException):
    container: Any
    exit_status: Any
    command: Any
    image: Any
    stderr: Any
    def __init__(self, container, exit_status, command, image, stderr) -> None: ...

class StreamParseError(RuntimeError):
    msg: Any
    def __init__(self, reason) -> None: ...

class BuildError(DockerException):
    msg: Any
    build_log: Any
    def __init__(self, reason, build_log) -> None: ...

class ImageLoadError(DockerException): ...

def create_unexpected_kwargs_error(name, kwargs): ...

class MissingContextParameter(DockerException):
    param: Any
    def __init__(self, param) -> None: ...

class ContextAlreadyExists(DockerException):
    name: Any
    def __init__(self, name) -> None: ...

class ContextException(DockerException):
    msg: Any
    def __init__(self, msg) -> None: ...

class ContextNotFound(DockerException):
    name: Any
    def __init__(self, name) -> None: ...
