from ..constants import IS_WINDOWS_PLATFORM as IS_WINDOWS_PLATFORM
from typing import Any

DOCKER_CONFIG_FILENAME: Any
LEGACY_DOCKER_CONFIG_FILENAME: str
log: Any

def find_config_file(config_path: Any | None = ...): ...
def config_path_from_environment(): ...
def home_dir(): ...
def load_general_config(config_path: Any | None = ...): ...
