from ..errors import StreamParseError as StreamParseError
from typing import Any

json_decoder: Any

def stream_as_text(stream) -> None: ...
def json_splitter(buffer): ...
def json_stream(stream): ...
def line_splitter(buffer, separator: str = ...): ...
def split_buffer(stream, splitter: Any | None = ..., decoder=...): ...
