from ..transport import NpipeSocket as NpipeSocket

STDOUT: int
STDERR: int

class SocketError(Exception): ...

def read(socket, n: int = ...): ...
def read_exactly(socket, n): ...
def next_frame_header(socket): ...
def frames_iter(socket, tty): ...
def frames_iter_no_tty(socket) -> None: ...
def frames_iter_tty(socket) -> None: ...
def consume_socket_output(frames, demux: bool = ...): ...
def demux_adaptor(stream_id, data): ...
