from .resource import Collection as Collection, Model as Model
from typing import Any

class Node(Model):
    id_attribute: str
    @property
    def version(self): ...
    def update(self, node_spec): ...
    def remove(self, force: bool = ...): ...

class NodeCollection(Collection):
    model: Any
    def get(self, node_id): ...
    def list(self, *args, **kwargs): ...
