from .. import errors as errors
from .resource import Collection as Collection, Model as Model
from typing import Any

class Plugin(Model):
    @property
    def name(self): ...
    @property
    def enabled(self): ...
    @property
    def settings(self): ...
    def configure(self, options) -> None: ...
    def disable(self) -> None: ...
    def enable(self, timeout: int = ...) -> None: ...
    def push(self): ...
    def remove(self, force: bool = ...): ...
    def upgrade(self, remote: Any | None = ...) -> None: ...

class PluginCollection(Collection):
    model: Any
    def create(self, name, plugin_data_dir, gzip: bool = ...): ...
    def get(self, name): ...
    def install(self, remote_name, local_name: Any | None = ...): ...
    def list(self): ...
