from typing import Any

class Model:
    id_attribute: str
    client: Any
    collection: Any
    attrs: Any
    def __init__(
        self,
        attrs: Any | None = ...,
        client: Any | None = ...,
        collection: Any | None = ...,
    ) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    @property
    def id(self): ...
    @property
    def short_id(self): ...
    def reload(self) -> None: ...

class Collection:
    model: Any
    client: Any
    def __init__(self, client: Any | None = ...) -> None: ...
    def __call__(self, *args, **kwargs) -> None: ...
    def list(self) -> None: ...
    def get(self, key) -> None: ...
    def create(self, attrs: Any | None = ...) -> None: ...
    def prepare_model(self, attrs): ...
